### ISSUE TITLE
Insert token with Serial Number XXXXX

### ISSUE THREAD

**Issue by rvalle** [chris2511/xca#115]
XCA es not allowing me to renew a certificate of a token backed CA

It is a strange issue I don't remember having before:
```
Please insert card: CardName#PKCS15 with Serial: NNNNNNNN
```
According to Manage Sercurity Token, the  troken with Serial NNNNNN is inserted.
Perhaps this issue is related to issue #83 , however, I have never transferred objects between tokens or whatsoever.

I just think that, for some reason, XCA does not recognise the right token as such.

Any idea what this could be about?

**Comment by rvalle** [comment]
just noticed that my fedora 29 comes with xca 1.4.1, 
however I have downloaded and compiled latest version 2.1.2
and the issue affects both versions.

**Comment by rvalle** [comment]
tried OSX and Linux... issue affects both.

**Comment by chris2511** [comment]
Please compare the name and serial in the details dialog of the token key to the values displayed in the "Manage token" dialog.
If they differ, you're affected by issue #83.
Please delete and re-import the token key to fix the issue.

Transferring objects is not the only source of the issue, just a reproducible one.
An updated or otherwise different PKCS#11 library may report a different label or serial.

**Comment by rvalle** [comment]
I think the Serial Numbers are the same, but I am going to test to re-import the token key anyway.

**Comment by rvalle** [comment]
@chris2511 deleting and re-importing the token objects did fix the issue.
Yes, probably it is an issue of versioning of PKCS#11 Library (OpenSC) which had some issues on recent releases for the particular token: epass2003. 

But now it all works! the certificate was renewed.

Many thanks.
