### ISSUE TITLE
Issue generating certificate for ECC key on a token

### ISSUE THREAD

**Issue by kategray** [chris2511/xca#151]
Trying to generate a root certificate authority based on an existing key, I get an error:

```
The following error occurred:
(8pki_x509[]:Aerobatt)
error:0D0DC006:asn1 encoding routines:ASN1_item_sign_ctx:EVP lib

(pki_x509.cpp:585)
```

I'm using ISOApplet on a Javacard, with the OpenSC PKCS11.  It's possible it's related to this issue, in which case it wouldn't be an XCA problem.

https://github.com/OpenSC/libp11/issues/34

**Comment by chris2511** [comment]
Right now I had the same issue with an ECC supporting card and the error message above.

In my case it was an unsupported hash-algo. Selecting SHA1 instead of SHA256 made it work.
XCA has an option "Only use hashes supported by the token when signing with a token key".
With this checked, it automatically selected SHA1 and the signature succeeded.

Please close the issue if your problem is solved.

**Comment by kategray** [comment]
Looks like that may be it (from IsoApplet):

```
else if(algRef == ALG_ECDSA_SHA1) {
                // Key reference must point to a EC private key.
                if(keys[privKeyRef].getType() != KeyBuilder.TYPE_EC_FP_PRIVATE) {
                    ISOException.throwIt(ISO7816.SW_DATA_INVALID);
                }
                if(ecdsaSignature == null) {
                    ISOException.throwIt(ISO7816.SW_FUNC_NOT_SUPPORTED);
                }

            } else {
                // No known or supported signature algorithm.
                ISOException.throwIt(ISO7816.SW_FUNC_NOT_SUPPORTED);
```

I’ll look into implementing additional algorithms.
