### ISSUE TITLE
Issues importing CRL

### ISSUE THREAD

**Issue by szisti** [chris2511/xca#153]
I have 2 CRLs one created by xca the other one while signed by the same CA was generated by a different application
Importing the 1st one to xca works perfectly fine, without an issues, but the other cannot be imported
I've tried to check it any way i could think of using openssl, but i never got any error messages

```
for i in xca_crl.pem crl.pem; do echo $i; openssl crl -in $i -CAfile IntermediateCA.pem -hash -noout; done
xca_crl.pem
verify OK
1a1dcb17
crl.pem
verify OK
1a1dcb17
```
I'm getting the following error:
```
The following error occurred:
Unable to load the revocation list in file crl.pem. Tried PEM and DER formatted CRL.
```
If I go and manually put this into the DB i get:
```
The following error occurred:
error:0D07209B:asn1 encoding routines:ASN1_get_object:too long
error:0D068066:asn1 encoding routines:asn1_check_tlen:bad object header
error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error
```
Anyone has any suggestion on what could be wrong with the second crl?

**Comment by chris2511** [comment]
> Anyone has any suggestion on what could be wrong with the second crl?

No, not without looking at the CRLs.
You may post it here or send it via email.

**Comment by szisti** [comment]
Thank you Chris
sent you the certificates in email

**Comment by chris2511** [comment]
The "other" application uses OCTET_STRING for the CRL number instead of INTEGER:

https://tools.ietf.org/html/rfc5280#section-5.2.3

$ openssl asn1parse < crl.pem | tail -n 6
  908:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 CRL Number
  913:d=5  hl=2 l=   2 prim: OCTET STRING      :19
  917:d=1  hl=2 l=  13 cons: SEQUENCE          
  919:d=2  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
  930:d=2  hl=2 l=   0 prim: NULL              
  932:d=1  hl=4 l= 257 prim: BIT STRING        

$ openssl asn1parse -inform DER < xca_crl.der | tail -n 6
  920:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 CRL Number
  925:d=5  hl=2 l=   3 prim: OCTET STRING      [HEX DUMP]:020112
  930:d=1  hl=2 l=  13 cons: SEQUENCE          
  932:d=2  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
  943:d=2  hl=2 l=   0 prim: NULL              
  945:d=1  hl=4 l= 257 prim: BIT STRING        

Even though the second one looks odd, it is correct: 0x020112 is the ASN1 encoding of the integer 18.
The first CRL erroneously contains ASCII "19" (0x3139).

I think the other application badly encoded the CRL number.
The OpenSSL cmdline application is flexible enough to ignore the error.

**Comment by szisti** [comment]
Thank you Chris for the help, everything works perfectly now
