### ISSUE TITLE
Apple silicon (M1) compatibility hints

### ISSUE THREAD

**Issue by SharkyRawr** [chris2511/xca#247]
This is maybe more of an documentation hint/footnote thing but I compiled xca for M1 with a few minor hiccups and pitfalls:

- configure needs `LDFLAGS="-L/opt/homebrew/Cellar/libtool/2.4.6_2/lib -L /opt/homebrew/Cellar/openssl@1.1/1.1.1i/lib"` and `CXXFLAGS="-I/opt/homebrew/Cellar/libtool/2.4.6_2/include -I/opt/homebrew/Cellar/openssl@1.1/1.1.1i/include"` as well as CFLAGS with the same content as CXXFLAGS (maybe optional? is there any C code?)
- somehow on m1/brew/new xcode(?) libraries get mangled sometimes and that makes them loose their signature as well as making re-signing difficult (this seems like a bug in the xcode tool `codesign`) -- so, once `make` has finished I had to copy an original libltdl.dylib (which is already signed) over the one the build script already copied: `cp /opt/homebrew/Cellar/libtool/2.4.6_2/lib/libltdl.7.dylib /Users/sophie/checkouts/xca/xca-2.3.0.103/xca.app/Contents/Frameworks/libltdl.7.dylib`
- After all that you can finally re-sign the app bundle because Big Sur requires all apps to be signed: `codesign -s YOURCERTIDENTITYHERE --force -vvvv --deep xca-2.3.0.103/xca.app` and you're done if it didn't throw any errors.

I made a zip of the app bundle in my personal repo SharkyRawr/m1-builds@50cbdea76e39da6da59c43e4cf8077431f5a5c1e signed with my local dev key which will likely throw a warning but it does work on my M1. :)

**Comment by chris2511** [comment]
Did you `brew install pkg-config`. It should autodetect the OpenSSL and libtool CFLAGS/LDFLAGS

**Comment by sleiner** [comment]
I just tried compiling xca on M1 (macOS 11.3) and had similar issues:

- libtool, although installed using homebrew was not found by pkgconfig, so the additional `CFLAGS`, `CXXFLAGS` and `LDFLAGS` are needed. I did notice that openssl contains `.pc` files:

  ```
  /opt/homebrew/Cellar/openssl@1.1/
  └── 1.1.1k
      ├── AUTHORS
      ├── CHANGES
      ├── INSTALL_RECEIPT.json
      ├── LICENSE
      ├── NEWS
      ├── README
      ├── bin
      │   ├── ...
      ├── include
      │   └── ...
      ├── lib
      │   ├── ...
      │   └── pkgconfig
      │       ├── libcrypto.pc
      │       ├── libssl.pc
      │       └── openssl.pc
      └── share
  ```

  libtool, however, does not contain any `.pc` files, not even a `lib/pkgconfig` subfolder. @chris2511 do you know if this is a homebrew problem, a libtool problem or something else.

  My workaround on the commandline is:

  ```zsh
  export CFLAGS="$CFLAGS -I$(find $(brew --cellar libtool) -type d -name "include" | sort -n | tail -n 1)"
  export CXXFLAGS="$CXXFLAGS -I$(find $(brew --cellar libtool) -type d -name "include" | sort -n | tail -n 1)"
  export LDFLAGS="$LDFLAGS -L$(find $(brew --cellar libtool) -type d -name "lib" | sort -n | tail -n 1)"
  ```

- The xca repo root somehow ends up in the include path list. Having a `VERSION` file in the include path messes with clang stdlib internals and causes the compilations to fail, e.g.
  ```
    CC     [lib] db_crl.o
  In file included from db_crl.cpp:9:
  In file included from ./db_crl.h:11:
  In file included from ./db_x509super.h:12:
  In file included from ./db_key.h:11:
  In file included from ./db_base.h:11:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/typeinfo:60:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/exception:80:
  In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cstddef:37:
  /Users/simon/repos/xca/version:1:1: error: expected unqualified-id
  2.3.0
  ```
  I got around that problem by compiling from a strictly case-sensitive filesystem, but there's probably a way to fix this even on a case-insensitive volume.
- In `configure.ac`, `/usr/local/Cellar` is hardcoded. I just replaced it with `$(brew --cellar)`.
- I did **not** need to perform any manual signing in order to run the app without any warnings :)

I will open a pull request that will add the automatic libtool discovery and also will get rid of the hardcoded homebrew paths :)

**Comment by chris2511** [comment]
man brew:
```
    --prefix [--unbrewed] [--installed] [formula ...]
       Display Homebrew's install path. Default:

       o   macOS Intel: /usr/local

       o   macOS ARM: /opt/homebrew
```
On my Intel /usr/local/[include|lib] is automatically in the search path and they contain
`/usr/local/include/ltdl.h` and `/usr/local/lib/libltdl.dylib`.
I assume you will find `ltdl.h` in /opt/homebrew/include

I pushed an improved configure, asking you to test it.

**Comment by sleiner** [comment]
> On my Intel /usr/local/[include|lib] is automatically in the search path and they contain
> /usr/local/include/ltdl.h and /usr/local/lib/libltdl.dylib.
> I assume you will find ltdl.h in /opt/homebrew/include
Yep, it's there 👍🏻

I tried building it with your patch and it failed at first. In order to get the build to work, I had to **remove the homebrew installed Qt6** (the one installed by the `qt` formula). Without your patch, Qt6 was ignored.
With Qt6 installed, `XCA_COMPILE_TEST` failed.
But I guess, there's probably a better way to solve that problem than being as specific with the flags as I was. Stylistically, I like your patch better than mine :)

**Comment by chris2511** [comment]
With this change it works even with an installed qt formula (at least for me :-)

**Comment by sleiner** [comment]
for me too 🚀

**Comment by sleiner** [comment]
Do you see any possibility for distributing official arm64 builds? Maybe trough the homebrew infrastructure?
