### ISSUE TITLE
generate CRL chain

### ISSUE THREAD

**Issue by harridu** [chris2511/xca#346]
AFAIU an intermediate CA (signed by a self-signed root CA) can be compromised, too, making it necessary to revoke such a certificate. So I wonder why the CA option in the context menu of a self-signed certificate is greyed out?

Would it be possible to generate a CRL **chain** for web server certificates, for example? I am not sure about the exact circumstances, but I had the case that a CRL was rejected because the root CRL was not included.

**Comment by Andy-2639** [comment]
Each CRL must be in it's own file, otherwise browsers don't read all CRLs https://stackoverflow.com/questions/60639728/output-all-crls-in-concatd-crl-file

A X.509 certificate cannot revoke itself but only its direct children. So if there is no parent CA, there's no possibility to revoke a certificate. (And the client has to get the revocation information from somewhere, so the certificate which might get revoked should (has) to point to the CRL/OCSP location where the revocation information are contained in.

**Comment by harridu** [comment]
@Andy-2639, I am not talking about revoking the root CA. AFAIU xca's context menu on a CA deals with the set of derived certificates (node or sub-CA) only. I just do not see why this has been greyed out in the context menu of the root CA.

About the "CRL chain". I agrre with you, but that doesn't help. I am bound by the implementation in the controller software (some remote management card).

**Comment by chris2511** [comment]
> AFAIU an intermediate CA (signed by a self-signed root CA) can be compromised, too, making it necessary to revoke such a certificate. So I wonder why the CA option in the context menu of a self-signed certificate is greyed out?

The CA Sub-menu is only available if the "Basic Constraints" is set tot TRUE and the private key is available.
Otherwise you cannot issue certificates or CRLs.
