### ISSUE TITLE
XCA building from sources in macOS won't work

### ISSUE THREAD

**Issue by klanomath** [chris2511/xca#49]
While trying to resolve XCA backwards compatibility issues already mentioned in [another thread](https://github.com/chris2511/xca/issues/30) I had to realize that building the app from the source with the given instructions in INSTALL.mac won't work here.

My environment: macOS 10.13.6 & Xcode 9.4.1

1st issue: **configure** won't be created with line 54 in build-mac.sh: (cd $XCA_DIR && ./bootstrap).

I tried to resolve it by installing the probably missing _automake_ and _autoconf_ with [brew](https://brew.sh/).

2nd issue: after installing automake/autoconf **configure** will be created but its execution stops at line ~2695 trying to detect some OpenSSL parameters. This can be resolved by hacking the configure file. But moreover - some lines later (~2770) - configure stops at detecting the Qt version.

Any hints?

**Comment by kaorihinata** [comment]
Unfortunately, the build/install documents are a confusing jumble and need to be simplified and rewritten. The process I've been using to build is actually (somewhat?) documented in the base INSTALL file, but there are also some problems with the build system that I should probably submit issues for. I'll leave that for another time though, in the meantime let me get you through the build process.

First off, while you do need automake and autoconf (as you found), you will also need libtool and pkg-config. Additionally, pkg-config is needed **before** running bootstrap. The generated configure file will be garbage without pkg-config as it provides a few macros used in configure.ac. On the other hand, omitting libtool emits a slightly more straight forward error when you run configure indicating that libltdl is missing.

For Qt5, while I know it's available in Homebrew (or at least was), I used the official installer which installs files into /Users/${USER}/Qt. There's no reason you shouldn't be able to use the Homebrew for Qt5, but I haven't tested it.

Once you have all of those installed, you can now run the bootstrap script which should generate a complete configure script. Since you're on macOS, you may want to go the route I did and pass in Qt5 and OpenSSL's paths directly to the configure script. It's indicated that you can do so in INSTALL, and there's an actual example in INSTALL.qt5. The environment variables aren't necessary though. I ended up running the following:

```sh
$ ./bootstrap
$ ./configure --with-openssl="/usr/local/Cellar/openssl/1.0.2p" \
              --with-qt="/Users/${USER}/Qt/5.11.1/clang_64"
$ make -j5 xca.dmg
```

There are a few gotchas, however:

1. The name of the code signing identity is hard coded into the Makefile. You will need to modify the identity name on line 163 to specify your own code signing identity.
2. The configure script generates misc/Info.plist (from misc/Info.plist.in), but both "make clean" and "make distclean" delete it. If you have any issues while building and need to clean and start again, you're going to have to run configure again too.
3. You cannot currently build XCA with LibreSSL due to function signature differences (, so you'll need to use OpenSSL, or submit a patch to handle the differences.

If you have any questions with regard to building XCA for macOS, I should (probably?) be able to help you out. Let me know if you have any issues.

Thomas

**Comment by chris2511** [comment]
Hi Thomas,

You are very welcome to improve the XCA build procedure and documentation for MacOSX.
I appreciate it.
Only very few people build XCA on Mac or Windows, so that procedure is optimized for me and my
environment.

1. LibreSSL should work since: https://github.com/chris2511/xca/issues/24
2. Deleting `misc/Info.plist` should be done in `distclean`, not in `clean`. Will fix that soon.

Thanks and regards

Christian

**Comment by olvrlrnz** [comment]
I managed to build it from source on my machine

    $ sw_vers
    ProductName:	Mac OS X
    ProductVersion:	10.14.2
    BuildVersion:	18C54

using the newest Xcode

    $ xcodebuild -version
    Xcode 10.1
    Build version 10B61

doing the following:

1. `brew install pkg-config autoconf automake openssl qt`
2. `cd ~/src`
3. `git clone https://github.com/chris2511/xca.git`
4. `cd xca`
5. `./bootstrap`
6. `mkdir build && cd build`
7. `../configure --prefix=/tmp/xca --with-openssl=/usr/local/opt/openssl --with-qt=/usr/local/opt/qt`
8. replace in Makefile (near bottom):
	\- `-codesign --force --deep --signature-size=96000 -s "Christian Hohnstaedt" $(DMGSTAGE)/xca.app --timestamp`
	\+ `-codesign --force --deep --signature-size=96000 -s "YOUR SIGNING IDENTITY" $(DMGSTAGE)/xca.app --timestamp`
9. `make -j$(sysctl -n hw.logicalcpu)`

**Comment by chris2511** [comment]
See also #136
