### ISSUE TITLE
Exporting PEM+PKCS#8.pem doesnt export encrypted private key

### ISSUE THREAD

**Issue by judders** [chris2511/xca#497]
xca-portable-2.5.0

Exporting Certificate with format PEM + PKCS#8 (*.pem) does not export encrypted private key.
Does not even ask for password.

xca-portable-2.4.0 working OK.

**Comment by spljaa** [comment]
For some private keys, they were exported as 0 size files.
Used 2.4.0 portable to export all content from database. And then reimported it on 2.5.0 (Fedora) into new database.
After import keys seem to work fine -> now exporting from 2.5.0 works for all.
From end-user perspective feels like something inside database (quite old one) does not get well with 2.5.0. 
I did not spend yet time to dig into it - my first impression is that problem is with older keys. But I do not have easy way to tell which version of XCA created the database. Or which version stored keys that are not exportable.

**Comment by judders** [comment]
Hey Spljaa.

I used a brand new database using 2.5.0 There was no keys imported from an old database.
2.4.0 is working fine, using the database created in 2.5.0.

**Comment by chris2511** [comment]
This is fixed with #465 for the next release
