### ISSUE TITLE
XCA Tool v2.5.0 remote database (mysql) broken with current Windows 11 Updates

### ISSUE THREAD

**Issue by OMSKremer** [chris2511/xca#516]
Hi,

i think, since some weeks (dont know exact when) a windows update/change killed xca-tool feature to connect to a mysql database source (xca-tool v2.5.0). Confirmed with 3 windows 11 clients.

Error message at connect try:
"Der folgende Fehler ist aufgetreten:
Driver not loaded Driver not loaded"

after an downgrade of xca-tool to v2.4.0 it works again.

I saw in the installation process of v2.4.0 for database drivers the mysql driver ... i checked again the v.2.5.0 .msi and there was only the ODBC and postgresql driver listed, not the mysql one.

Theories:
- Version 2.5.0 never worked, so I used version 2.4.0 the whole time and there was an update the last weeks, after i used the last time xca-tool, that I didn't recognize. ( i dont think so)
- The (xca-tool included?) driver for/from v2.5.0 is not "valid" anymore?! So it doesnt show up in the install process?
- There was a change and mysql/maraiadb is generally not supported anymore? (Cant find such a hint in the changelogs)
![2024-02-05 10_25_45-XCA Setup](https://github.com/chris2511/xca/assets/1644266/30903f89-6cdb-4ce1-a43e-18b878b09923)

**Comment by chris2511** [comment]
The [Release Notes](/chris2511/xca?tab=readme-ov-file#release-notes) state:
 - Drivers for SQL Servers must be [installed separately](https://github.com/chris2511/xca?tab=readme-ov-file#sql-remote-database-drivers) since 2.5.0

MariaDB (MySQL): Install the Plugin from here: https://github.com/thecodemonkey86/qt_mysql_driver. Select the MinGW variant and install it as documented.
