### ISSUE TITLE
Export certificates for ovpn file

### ISSUE THREAD

**Issue by reetp** [chris2511/xca#518]
It would be very handy indeed to have an export of the certificates to a ovpn type file.

Include the CA, Cert and Key, and a TA key as well would be even better :-)

Format is like this:

```
<ca>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</ca>
<key>
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----
</key>
<cert>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</cert>
<tls-auth>
-----BEGIN OpenVPN Static key V1-----
-----END OpenVPN Static key V1-----
</tls-auth>

```

Even just putting all three into one file so we can add the codes after would be a big help - it's a lot of cutting and pasting otherwise!

**Comment by chris2511** [comment]
Adding support for the static key needs a little more work, since it must be generated once as property of the CA and stay the same for all certs issued by the "openvpn" CA.

You may try the requested feature, implemented with 0a1a21608db191af11f79ff5bd85e895521e1625 from [one of this builds](https://github.com/chris2511/xca/actions/runs/7858105859)

**Comment by reetp** [comment]
Fabulous and thanks!

I'll try a build later.

**Comment by reetp** [comment]
Just built from develop and it looks fine!
