### ISSUE TITLE
New XCA v2.6.0 - It's not in English

### ISSUE THREAD

**Issue by SemoTech** [chris2511/xca#532]
Hello, 

I use the Darwin DMG in MacOS Monterey, so just dowloaded (from GitHub) and replaced my XCA v2.5.0 with XCA v2.6.0 and noticed it is not in English!
![image](https://github.com/chris2511/xca/assets/1452100/43e72b79-5af3-484b-9759-c66d6c12df35)

I subsequently downloaded v2.6.0 from the Mac App Store, and got this:
![image](https://github.com/chris2511/xca/assets/1452100/61c7ec6b-e431-418a-ac76-e3c55d4e2522)

Looks like both locations have XCA defaulting to non-English and I cannot seem to find a way to change the language to English.  

Lastly, even running the old XCA v2.5 that was always in English now defaults to non-English as the new version must have changed/left some other core files on my Mac. 

Please advise.

Thank you.

**Comment by chris2511** [comment]
XCA assumes your system language is Indonesian.
It is stored in the file */Users/<YOURNAME>/Library/Application Support/xca/defaultlang*

In the menu select *Berkas* -> *Bahasa* -> *inggris (English)*

**Comment by SemoTech** [comment]
Thank you @chris2511 that worked.  

Now why would XCA assume my system language is Indonesian when this is an English install and there are no apps doing this or any settings anywhere that have anything to do with Indonesia?

And seems not all sections were translated back into English from Indonesian:
![image](https://github.com/chris2511/xca/assets/1452100/9d1a3d1a-4134-4ca3-9914-931d578935f0)

And lastly, most important I had an existing .xdb file called "Personal.xdb" and the new XCA v2.6.0 no longer has a Menu option to open a database.  If I right click on "Personal.xdb" and open with XCA I get a notice about old security:
![image](https://github.com/chris2511/xca/assets/1452100/7f37f387-dc64-4aa1-8712-2e728d26aef0)

If I choose ignore a database called "default.xdb" opens and it is empty!
![image](https://github.com/chris2511/xca/assets/1452100/b35938a9-0eb5-4d17-a2f2-5653019960ff)

If I choose "change" and switch encryption it again opens empty!!

**_Where are all all my certificates and private keys???_**

Thanks.

**Comment by chris2511** [comment]
The Appstore variant uses a fixed database *default.xdb*
Please install the DMG file. It will open your database successfully.

**Comment by SemoTech** [comment]
> The Appstore variant uses a fixed database _default.xdb_ Please install the DMG file. It will open your database successfully.

OK, that part was not intuitive and good to know that the App Store version cannot use anyting but the default database and I guess is missing the [File] and [Token] Menus on purpose I suppose.  

I was able to get my database loaded and upgraded the encryption on it.  Thank you.

Please note the Indonesian default/system language option seems to be hardcoded as in v2.5 it is correctly detected as English but both App store and Github versions of XCA 2.6 default to Indonesian.  Even after changing to English there are still stragglers in other languages:
![image](https://github.com/chris2511/xca/assets/1452100/4b3b9d31-1afc-4d42-8dc2-380c4fbf01d9)

Lastly in the Github version 2.6.0 if you open a custom database, enter the password and it loads, then you quit XCA and restarts it opens without the database (does not remember the last database used) like v2.5 used to and you have to manually re-load it from the File menu

Thank you.

**Comment by chris2511** [comment]
Select "Set as default database" when the preferred database is open and it will be opened automatically next time.

**Comment by SemoTech** [comment]
> Select "Set as default database" when the preferred database is open and it will be opened automatically next time.

Brilliant.  Works great @chris2511 thank you.

I guess all that remains and needs fixing, that I know of, for v2.6.0 is the language issues.

**Comment by Lotusshaney** [comment]
Any ideas on this problem ?

**Comment by DocCyblade** [comment]
Was going to give this software a try and well it does not come up in English on MacOS. As the above have said. I think it may because English is not listed in the info.plist file? 

I noticed the en_US was missing from the list. I hacked it (you should not do that, MacOS will find out and the signed hashes won't match it will not run the app. However if you do this quickly it works for the first run then app won't start by design) and added the missing option and it works. So looks like the app options need updated. Hope this helps!


**plist file before changed**
![Screenshot 2024-03-07 at 3 48 01 PM](https://github.com/chris2511/xca/assets/9731860/bd76bf51-2017-44ac-905a-9aca7a32ea04)

**When run you get this**
![Screenshot 2024-03-07 at 3 48 25 PM](https://github.com/chris2511/xca/assets/9731860/0e845ed9-bbc7-4266-905b-25e8569e6c7b)

and

![Screenshot 2024-03-07 at 3 49 39 PM](https://github.com/chris2511/xca/assets/9731860/fa157c93-cece-4328-b23d-db0425b02651)


**Updated the plist file (hacked it)**
![Screenshot 2024-03-07 at 3 48 43 PM](https://github.com/chris2511/xca/assets/9731860/057c8016-3c20-4d92-947e-69d01ee9ea97)

**Now you get English**

![Screenshot 2024-03-07 at 3 48 58 PM](https://github.com/chris2511/xca/assets/9731860/e80dd2f4-6adf-49f6-b3d6-8c3611dc51d0)


![Screenshot 2024-03-07 at 3 50 01 PM](https://github.com/chris2511/xca/assets/9731860/08c8f6b6-1351-4c46-b798-04e6c136fcf7)

**Comment by Lotusshaney** [comment]
Get @DocCyblade a beer, 100% works !
