### ISSUE TITLE
Disorder in displaying Persian words that are links

### ISSUE THREAD

**Issue by Erfankam** [chris2511/xca#549]
We have problem while showing Persian characters that are links. Any idea?
I have attached a picture showing this error.
![xca-persian-character-bug](https://github.com/chris2511/xca/assets/1054901/8bb0c132-fdb9-4bf8-adb2-e3f64641704b)

**Comment by Erfankam** [comment]
@chris2511 Could I work on this, if you consider it as a bug?
It yes, please assign it to me.
Thanks.

**Comment by chris2511** [comment]
I don't see the issue. Presumably because I can't read / grasp persian at all.
Maybe if you come up with the solution, I understand the problem. :-)

**Comment by Erfankam** [comment]
To describe the problem, e.g. the correct form of file translation in Persian is "پرونده". But as you see, the first letter of the word (پ), comes in the form of "پ" instead of form "پـ", so we must see word as "پرونده" (correct form) instead of "پ‌رونده" (wrong form).
Seems this problem occurs when the word is underlined for shortcuts.

**Comment by chris2511** [comment]
I don't think we can fix that.
Since the isolated and initial variant of "پ" have the same Unicode codepoint U+067E https://en.wikipedia.org/wiki/Pe_(Persian_letter) it is the responsibiity of the characterset and QT to render it as initial, even if it is underlined and the rest of the word is not.

Does the shortcut to open the File menu actually work?

**Comment by Erfankam** [comment]
All shortcuts are working properly.
You are right about character codepoint of "پ" and form of character in Qt.
