### ISSUE TITLE
[Feature request] possibility to ignore password prompt from CLI

### ISSUE THREAD

**Issue by KervyN** [chris2511/xca#67]
Hi,
I'd like to export the certificate index via CLI. Is it somehow possible to not come up with a password prompt?

`xca ca.xdb -x -i ~/index.txt` comes up with a password prompt, which can just get dismissed via cancel. 
I have no idea how to work around this for automation.

**Comment by chris2511** [comment]
1.) The quick and ugly workaround: Remove the password from the database (Change database password to an empty string) and leave the keys unprotected :-(

1.a) Create a 2nd database without private keys and drop all certificates and CRLs generated in the first db to the second db, and use it for the index. (Still ugly, additionally cumbersome, but secure)

2.) A quick-to-implement fix could be a command-line parameter to open the database without asking for the password, because for the index no private keys are required and thus no password. Anyway, XCA still requires an X Server to connect to. It always does. (Try "DISPLAY=bummer xca -v").

3.) Completely split UI and database engine -> Much coding work for me! But I deserve it, because the mix of UI and database functionality is Bad Design.

4.) Hack a shell/python-script, using sqlite3 and openssl to generate the index file.

**Comment by KervyN** [comment]
We are currently working with the 1.a approach :-)
We thought about 4 but don't know enough to come far enough, because certificate attributes are not stored inside the DB, but only the cert. :-)

**Comment by AnonATXDO** [comment]
Hello! 

Thank you for the update. 

I thought this would fix the issue, if I have a separate password for a key and want to use it to create a CRL. E.g. my Key "A" has a different password then the database password - but I want to create the CRL for Zertifikate "X" which was signed by "A", then I have no way to do it through the CLI without GUI, or have I?
